// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlEwoylF66CkI4Rw7ReKa8LavSTLi8OaA',
    appId: '1:67937552375:web:9f8bfe93ef5225dc7a90f2',
    messagingSenderId: '67937552375',
    projectId: 'alarmforsleep',
    authDomain: 'alarmforsleep.firebaseapp.com',
    databaseURL: 'https://alarmforsleep-default-rtdb.firebaseio.com',
    storageBucket: 'alarmforsleep.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCio6m8NWaWUeNFnIegFF85ArW2XqvsX8Q',
    appId: '1:67937552375:android:89d9409399e0543c7a90f2',
    messagingSenderId: '67937552375',
    projectId: 'alarmforsleep',
    databaseURL: 'https://alarmforsleep-default-rtdb.firebaseio.com',
    storageBucket: 'alarmforsleep.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANExcQ7U4otAVLYideH-ucGFvE7JAPLYo',
    appId: '1:67937552375:ios:f8480310f8d0d9b37a90f2',
    messagingSenderId: '67937552375',
    projectId: 'alarmforsleep',
    databaseURL: 'https://alarmforsleep-default-rtdb.firebaseio.com',
    storageBucket: 'alarmforsleep.appspot.com',
    iosClientId: '67937552375-9ngkam3f8sohniahho4udsqpn7k7ivad.apps.googleusercontent.com',
    iosBundleId: 'com.example.a4s',
  );
}
